plugins/plugin_manager.py
static/themes/basic/base.css
templates/plugins.html

This fixes the links and tags for the brows vs browse spelling in the code.

Additional Typo Fix

---

README.md
gv.py
gv_reference.txt
sip.py
static/scripts/schedule.js
templates/base.html
templates/options.html
templates/stations.html
webpages.py

Let me know what you think.  thx

Enable per zone control over adjusting runtime based on water level

---

sip.py
sip.sh

Reference /home/pi/SIP instead of /home/pi/sip so /etc/init.d get correct directory for files.

directory name change

---

helpers.py
plugins/signaling_examples.py

- alarm_toggled
Document usage as implemented
- station_scheduled
Add a signal in helpers.schedule_stations() to signal when programs are
started

Add new Signals and examples

---

plugins/signaling_examples.py

fixes #163  reported by @mihugo

Fixes #163

---

templates/modify.html

In sequential mode, with individual station duration option set, the total time (_interval_) and the _endTime_ was not recalculated for single pass programs.

Correct interval and stop time when seq + idd + non-recurring program

---

sip.py

This fixes problems when a master station is used in concurrent mode.  The original code would stop the master when it should remain running.  The edited code also cleans up some inconsistencies in the style of the code.  I've been running the edited code for several days without problems.
-Chris

heegard-master-station-fix

---

helpers.py
sip.py
webpages.py

The changes fixed problems with programs in concurrent mode.  In particular,
if a programs starts a given station that was already running, then the
station failed to run correctly.  Also, fix to log so that running programs
are logged before a run-once proceeds.  Finally, a few inconsistant style
issues where edited.  Removed a few tabs (changed to spaces).
sip.py:
fixed problems in concurrent mode
fix for negative duration
cleaned notation (idx -> sid)
tabs -> spaces
webpages.py:
added log entries before run-once program is started
cleaned notation (i, v -> sid, dur)
helpers.py:
made conditional that rejects certain erroneous log entries

Made several changes to sip.py, webpages.py and helpers.py

---

gpio_pins.py
helpers.py

Hi, I've added support for Odroid-C2 board. It has slightly different wiringPi interface.

Odroid-C2 board support

---

plugins/signaling_examples.py

Just and example! -> Just an example!

Gramatical fix

---

README.md

Hi,
Finally I found time to make short instruction how to install SIP on Odroid-C2 (branch switching, manual relay_board plugin install, etc).
Hope it will help others.
Egidijus

Updated changelog, added link to Odroid-C2 instructions

---

helpers.py
sip.py
static/scripts/behaviors.js
templates/base.html
webpages.py

Simplify js usage, on temperature toggle by using the convert_temp function

Temperature Convertion  function

---

webpages.py

added additional object to status API to return system name, status, water level, rain delay, and mode.

added object to status API to return more parameters

---

helpers.py

subprocess returns byte, convert to Unicode

Fix for python 3

---

static/themes/basic/base.css
templates/modify.html
templates/programs.html

Program page had a class typo that was degrading the styling.  Did some minor tweaks in the Program edit page too.

Program & edit page Styling tweaks

---

gv.py

For some reason my previous commit f9bbe0c did not take - probably some kind of repo sync issue on my part.  Trying again - moving pnames initialization ahead of load_programs.

Retry patch for pnames

---

helpers.py
sip.py
static/scripts/schedule.js
templates/base.html

Update schedule view legend to use program_index.
Fix occasional scroll-bar appearance in schedule view.

Add program_index to log

---

static/scripts/schedule.js
templates/base.html
webpages.py

- Converted (broken) hover box in display to tool-tip, added adjustment value there
- Extended CSV download with program_index and adjustment
- Fixed log api where runs spilling over from previous night would not be provided if more than 60 minutes in length

Improvements related to extended log data

---

helpers.py
sip.py
static/scripts/schedule.js
static/themes/basic/base.css
templates/base.html
templates/home.html

- Improved Interval Program calculation
- Restore display in device timezone
- Improve temperature display for devices without temperature data
- miscellaneous schedule formatting polish

Synchronize interval program display and runs

---

.gitignore
gv_reference.txt
helpers.py
plugins/plugin_manager.py

Fixed bug with sub directory creation in install_plugins()
Retrieve SIP url from environment var
Standardise README and other file fetching
Add documentation  for wl_ and to run_once()
My editor remove whitespace from the end of lines so there are quire a few whitespace changes, these can be ignored in the file diff or if this is not desired I can rework the PR.

Fixed bug with sub directory creation in install_plugins()
